#!/usr/bin/env bash


# Define variables
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -N "$PASSPHRASE" -f $KEY_NAME

echo "RSA key pair created successfully!"
