#!/usr/bin/env bash
# 1-install_and_configure_haproxy

# Update the package list
sudo apt-get update

# Install HAproxy if it's not already installed
if ! command -v haproxy &> /dev/null; then
    sudo apt-get install -y haproxy
fi

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy to use web-01 and web-02 with round-robin algorithm
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # See: https://ssl-config.mozilla.org/#server=haproxy&version=2.0.3&config=intermediate
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 64002-web-01:80 check
    server web-02 64002-web-02:80 check
EOL'

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Verify the configuration
curl -Is localhost | grep X-Served-By
